services:
  nginx:
    image: nginx:mainline-alpine
    profiles:
      - prod
    volumes:
      - ./secrets/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - www
    ports:
      - '80:80'
    depends_on:
      create_certs:
        condition: service_completed_successfully
  ngrok:
    image: ngrok/ngrok:3-alpine
    profiles:
      - dev
    environment:
      - NGROK_CONFIG=/etc/ngrok.yml
    volumes:
      - ./secrets/ngrok/ngrok.yml:/etc/ngrok.yml:ro
    ports:
      - '4040:4040'
    networks:
      - www

  nginx-dev:
    image: nginx:mainline-alpine
    profiles:
      - dev
    volumes:
      - ./config/nginx_dev/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - www
    ports:
      - '8000:8000'
  redirect-dev:
    build:
      context: './config/redirect_dev'
    profiles:
      - dev
    volumes:
      - ./config/redirect_dev/app.py:/app.py
    networks:
      - www

  acme:
    build:
      context: './config/acme'
      args:
        acme_email: $acme_email
    profiles:
      - setup
    volumes:
      - ./secrets/acme/account.conf:/root/account.conf
      - acme:/root/.acme.sh

  create_certs:
    build:
      context: './config/create_certs'
    profiles:
      - prod
    volumes:
      - ./secrets/acme/account.conf:/root/account.conf:ro
      - ./config/create_certs/create_certs.sh:/root/create_certs.sh:ro
      - acme:/root/.acme.sh

networks:
  www:

volumes:
  acme:
