services:
  ngrok:
    image: ngrok/ngrok:3-alpine
    profiles:
      - dev
    environment:
      - NGROK_CONFIG=/etc/ngrok.yml
    volumes:
      - ./secrets/ngrok/ngrok.yml:/etc/ngrok.yml:ro
    ports:
      - '4040:4040'
    networks:
      - www

  nginx-dev:
    image: nginx:mainline-alpine
    profiles:
      - dev
    volumes:
      - ./config/nginx_dev/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - www
    ports:
      - '8000:8000'
  redirect-dev:
    build:
      context: './config/redirect_dev'
    profiles:
      - dev
    volumes:
      - ./config/redirect_dev/app.py:/app.py

    networks:
      - www
networks:
  www:
