networks:
  www:
  db:
  cache:
  app:
  ingress:
    name: ingress
    external: true

volumes:
  db:
  redis:
  pixelfed-bootstrap:
  pixelfed-storage:
services:
  app:
    image: ghcr.io/intentionally-left-nil/pixelfed-fpm:0.11.9-with-username-fix
    profiles:
      - prod
    restart: unless-stopped
    env_file: ./secrets/pixelfed/.env
    init: true
    volumes:
      - './secrets/pixelfed/.env:/var/www/.env'
      - './config/pixelfed/php.ini:/usr/local/etc/php/php.ini:ro'
      - pixelfed-storage:/var/www/storage
      - pixelfed-bootstrap:/var/www/bootstrap
    networks:
      app:
      db:
      cache:
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  worker:
    image: ghcr.io/intentionally-left-nil/pixelfed-fpm:0.11.9-with-username-fix
    profiles:
      - prod
    env_file: ./secrets/pixelfed/.env
    init: true
    volumes:
      - './secrets/pixelfed/.env:/var/www/.env'
      - './config/pixelfed/php.ini:/usr/local/etc/php/php.ini:ro'
      - pixelfed-storage:/var/www/storage
      - pixelfed-bootstrap:/var/www/bootstrap
    command: 'gosu www-data php artisan horizon'
    networks:
      app:
      db:
      cache:
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  periodic:
    build:
      context: './config/periodic'
    profiles:
      - prod
    env_file: ./secrets/pixelfed/.env
    volumes:
      - './secrets/pixelfed/.env:/var/www/.env'
      - './config/pixelfed/php.ini:/usr/local/etc/php/php.ini:ro'
      - pixelfed-storage:/var/www/storage
      - pixelfed-bootstrap:/var/www/bootstrap
    networks:
      app:
      db:
      cache:
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    build:
      context: './config/nginx'
    profiles:
      - prod
    restart: unless-stopped
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - pixelfed-storage:/var/www/storage:ro
    networks:
      ingress:
        aliases:
          - pixelfed
      www:
        aliases:
          - pixelfed
      app:
        aliases:
          - pixelfed
    depends_on:
      - app

  nginx_dev:
    build:
      context: './config/nginx'
    profiles:
      - dev
    restart: unless-stopped
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - pixelfed-storage:/var/www/storage:ro
    networks:
      www:
        aliases:
          - pixelfed
      app:
        aliases:
          - pixelfed
    depends_on:
      - app_dev
  db:
    image: postgres:alpine
    profiles:
      - setup
      - dev
      - prod
    restart: unless-stopped
    env_file: ./secrets/db/.env
    volumes:
      - db:/var/lib/postgresql/data/
      - ./config/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - db
    shm_size: 256m
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'postgres', '-U', 'postgres']
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  initialize:
    image: ghcr.io/intentionally-left-nil/pixelfed-fpm:0.11.9-with-username-fix
    profiles:
      - setup
    env_file:
      - ./secrets/pixelfed/.env
      - ./secrets/pixelfed/init.env
    volumes:
      - './secrets/pixelfed/.env:/var/www/.env'
    networks:
      - db
      - cache
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command:
      [
        '/bin/sh',
        '-c',
        'php artisan migrate --force && php artisan import:cities && php artisan instance:actor && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan passport:client --personal --name=pixelfed -n && php artisan horizon:install && php artisan horizon:publish && (php artisan user:create --name="$$ADMIN_DISPLAY_NAME" --email="$$ADMIN_EMAIL" --username="$$ADMIN_USER_NAME" --password="$$ADMIN_PASSWORD" --is_admin=1 --confirm_email=1 --no-interaction || true)',
      ]

  redis:
    image: redis:alpine
    profiles:
      - setup
      - dev
      - prod
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      - cache
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  backup:
    build:
      context: './config/backup'
    profiles:
      - prod
    restart: unless-stopped
    env_file: ./secrets/backup/.env
    environment:
      - BACKUP_ENVIRONMENT=prod
    networks:
      - db
    depends_on:
      db:
        condition: service_healthy

  # THE FOLLOWING SERVICES ARE ONLY NEEDED FOR THE DEV STACK
  # You can ignore the rest of this file when running on prod
  app_dev:
    image: ghcr.io/intentionally-left-nil/pixelfed-fpm:0.11.9-with-username-fix
    profiles:
      - dev
    env_file: ./secrets/pixelfed/dev.env
    init: true
    volumes:
      - './secrets/pixelfed/dev.env:/var/www/.env'
      - './config/pixelfed/php-development.ini:/usr/local/etc/php/php.ini:ro'
      - pixelfed-storage:/var/www/storage
      - pixelfed-bootstrap:/var/www/bootstrap
    command:
      [
        '/bin/sh',
        '-c',
        'cp -r storage.skel/* storage/ && chown -R www-data:www-data storage/ bootstrap/ && . /var/www/.env && php artisan config:cache && php artisan storage:link && php artisan horizon:publish && php artisan route:cache && php artisan view:cache && php-fpm',
      ]
    networks:
      app:
        aliases:
          - app
      db:
      cache:
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      app_dynamic_domain:
        condition: service_completed_successfully

  worker_dev:
    image: ghcr.io/intentionally-left-nil/pixelfed-fpm:0.11.9-with-username-fix
    profiles:
      - dev
    env_file: ./secrets/pixelfed/dev.env
    init: true
    volumes:
      - './secrets/pixelfed/dev.env:/var/www/.env'
      - './config/pixelfed/php-development.ini:/usr/local/etc/php/php.ini:ro'
      - pixelfed-storage:/var/www/storage
      - pixelfed-bootstrap:/var/www/bootstrap
    command: 'gosu www-data php artisan horizon'
    networks:
      app:
      db:
      cache:
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      app_dynamic_domain:
        condition: service_completed_successfully
  periodic_dev:
    build:
      context: './config/periodic'
    profiles:
      - dev
    env_file: ./secrets/pixelfed/dev.env
    volumes:
      - './secrets/pixelfed/dev.env:/var/www/.env'
      - './config/pixelfed/php-development.ini:/usr/local/etc/php/php.ini:ro'
      - pixelfed-storage:/var/www/storage
      - pixelfed-bootstrap:/var/www/bootstrap
    networks:
      app:
      db:
      cache:
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      app_dynamic_domain:
        condition: service_completed_successfully
  backup_dev:
    build:
      context: './config/backup'
    profiles:
      - dev
    env_file: ./secrets/backup/.env
    environment:
      - BACKUP_ENVIRONMENT=dev
    networks:
      - db
    depends_on:
      db:
        condition: service_healthy
  ngrok:
    image: ngrok/ngrok:3-alpine
    profiles:
      - dev
    environment:
      - NGROK_CONFIG=/etc/ngrok.yml
    volumes:
      - ./secrets/ngrok/ngrok.yml:/etc/ngrok.yml:ro
    ports:
      - '4040:4040'
    networks:
      - www
    healthcheck:
      test:
        ['CMD-SHELL', 'wget -O - localhost:4040/api/tunnels | grep public_url']
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  app_dynamic_domain:
    image: python:alpine
    profiles:
      - dev
    volumes:
      - ./config/app_dynamic_domain/app.py:/app.py
      - ./secrets/pixelfed/dev.env:/dev.env
    command: ['python', '/app.py']
    networks:
      - www
    depends_on:
      ngrok:
        condition: 'service_healthy'

  redirect_dev:
    build:
      context: './config/redirect_dev'
    profiles:
      - dev
    volumes:
      - ./config/redirect_dev/app.py:/app.py
    networks:
      - www
    ports:
      - '8000:8000'
