
networks:
  db:
  cache:
  app:
  ingress:
    name: ingress
    external: true

volumes:
  postgres-16:
  redis:
  pixelfed-storage:
services:
  app:
    image: ghcr.io/intentionally-left-nil/pixelfed:0.14.3
    profiles:
      - prod
    restart: unless-stopped
    env_file: ./secrets/pixelfed/.env
    init: true
    environment:
      SSL_MODE: 'off'
      PHP_POST_MAX_SIZE: '500M'
      PHP_UPLOAD_MAX_FILE_SIZE: '500M'
      PHP_OPCACHE_ENABLE: '1'
      AUTORUN_ENABLED: 'true'
      AUTORUN_LARAVEL_MIGRATION: 'true'
      AUTORUN_LARAVEL_MIGRATION_ISOLATION: 'true'
      AUTORUN_LARAVEL_STORAGE_LINK: 'true'
      AUTORUN_LARAVEL_EVENT_CACHE: 'true'
      AUTORUN_LARAVEL_ROUTE_CACHE: 'true'
      AUTORUN_LARAVEL_VIEW_CACHE: 'true'
      AUTORUN_LARAVEL_CONFIG_CACHE: 'true'
    volumes:
      - './secrets/pixelfed/.env:/var/www/html/.env'
      - pixelfed-storage:/var/www/html/storage
    networks:
      app:
      db:
      cache:
      ingress:
        aliases:
          - pixelfed
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  worker:
    image: ghcr.io/intentionally-left-nil/pixelfed:0.14.3
    profiles:
      - prod
    restart: unless-stopped
    env_file: ./secrets/pixelfed/.env
    init: true
    command: ['php', 'artisan', 'horizon']
    environment:
      AUTORUN_ENABLED: 'false'
      AUTORUN_LARAVEL_MIGRATION: 'false'
      AUTORUN_LARAVEL_MIGRATION_ISOLATION: 'false'
      AUTORUN_LARAVEL_STORAGE_LINK: 'true'
      AUTORUN_LARAVEL_EVENT_CACHE: 'false'
      AUTORUN_LARAVEL_ROUTE_CACHE: 'false'
      AUTORUN_LARAVEL_VIEW_CACHE: 'false'
      AUTORUN_LARAVEL_CONFIG_CACHE: 'true'
      PHP_POST_MAX_SIZE: '500M'
      PHP_UPLOAD_MAX_FILE_SIZE: '500M'
      PHP_OPCACHE_ENABLE: '1'
    volumes:
      - './secrets/pixelfed/.env:/var/www/html/.env'
      - pixelfed-storage:/var/www/html/storage
    networks:
      app:
      db:
      cache:
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'php', 'artisan', 'horizon:status']
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  periodic:
    image: ghcr.io/intentionally-left-nil/pixelfed:0.14.3
    profiles:
      - prod
    restart: unless-stopped
    env_file: ./secrets/pixelfed/.env
    command: ['php', 'artisan', 'schedule:work']
    stop_signal: SIGTERM
    environment:
      AUTORUN_ENABLED: 'false'
      AUTORUN_LARAVEL_MIGRATION: 'false'
      AUTORUN_LARAVEL_MIGRATION_ISOLATION: 'false'
      AUTORUN_LARAVEL_STORAGE_LINK: 'true'
      AUTORUN_LARAVEL_EVENT_CACHE: 'false'
      AUTORUN_LARAVEL_ROUTE_CACHE: 'false'
      AUTORUN_LARAVEL_VIEW_CACHE: 'false'
      AUTORUN_LARAVEL_CONFIG_CACHE: 'true'
      PHP_POST_MAX_SIZE: '500M'
      PHP_UPLOAD_MAX_FILE_SIZE: '500M'
      PHP_OPCACHE_ENABLE: '1'
    volumes:
      - './secrets/pixelfed/.env:/var/www/html/.env'
      - pixelfed-storage:/var/www/html/storage
    networks:
      app:
      db:
      cache:
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'healthcheck-schedule']
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  db:
    image: postgres:16-alpine
    profiles:
      - setup
      - dev
      - prod
    restart: unless-stopped
    env_file: ./secrets/db/.env
    volumes:
      - postgres-16:/var/lib/postgresql/data/
      - ./config/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - db
    shm_size: 256m
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'postgres', '-U', 'postgres']
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  initialize:
    image: ghcr.io/intentionally-left-nil/pixelfed:0.14.3
    profiles:
      - setup
    env_file:
      - ./secrets/pixelfed/.env
      - ./secrets/pixelfed/init.env
    volumes:
      - './secrets/pixelfed/.env:/var/www/html/.env'
    entrypoint: ['']
    networks:
      - db
      - cache
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command:
      [
        '/bin/sh',
        '-c',
        'php artisan migrate --force && php artisan import:cities && php artisan instance:actor && php artisan passport:client --personal --name=pixelfed -n && php artisan horizon:install && php artisan horizon:publish && (php artisan user:create --name="$$ADMIN_DISPLAY_NAME" --email="$$ADMIN_EMAIL" --username="$$ADMIN_USER_NAME" --password="$$ADMIN_PASSWORD" --is_admin=1 --confirm_email=1 --no-interaction || true)',
      ]

  redis:
    image: redis:alpine
    profiles:
      - setup
      - dev
      - prod
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      - cache
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  backup:
    build:
      context: './config/backup'
    profiles:
      - prod
    restart: unless-stopped
    env_file: ./secrets/backup/.env
    environment:
      - BACKUP_ENVIRONMENT=prod
    networks:
      - db
    depends_on:
      db:
        condition: service_healthy

  # THE FOLLOWING SERVICES ARE ONLY NEEDED FOR THE DEV STACK
  # You can ignore the rest of this file when running on prod
  app_dev:
    image: ghcr.io/intentionally-left-nil/pixelfed:0.14.3
    profiles:
      - dev
    env_file: ./secrets/pixelfed/dev.env
    init: true
    environment:
      SSL_MODE: 'off'
      PHP_POST_MAX_SIZE: '500M'
      PHP_UPLOAD_MAX_FILE_SIZE: '500M'
      PHP_OPCACHE_ENABLE: '1'
      AUTORUN_ENABLED: 'true'
      AUTORUN_LARAVEL_MIGRATION: 'true'
      AUTORUN_LARAVEL_MIGRATION_ISOLATION: 'true'
      AUTORUN_LARAVEL_STORAGE_LINK: 'true'
      AUTORUN_LARAVEL_EVENT_CACHE: 'true'
      AUTORUN_LARAVEL_ROUTE_CACHE: 'true'
      AUTORUN_LARAVEL_VIEW_CACHE: 'true'
      AUTORUN_LARAVEL_CONFIG_CACHE: 'true'
    volumes:
      - './secrets/pixelfed/dev.env:/var/www/html/.env'
      - pixelfed-storage:/var/www/html/storage
    ports:
      - '8080:8080'
    networks:
      app:
        aliases:
          - app
      db:
      cache:
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker_dev:
    image: ghcr.io/intentionally-left-nil/pixelfed:0.14.3
    profiles:
      - dev
    env_file: ./secrets/pixelfed/dev.env
    init: true
    command: ['php', 'artisan', 'horizon']
    environment:
      AUTORUN_ENABLED: 'false'
      AUTORUN_LARAVEL_MIGRATION: 'false'
      AUTORUN_LARAVEL_MIGRATION_ISOLATION: 'false'
      AUTORUN_LARAVEL_STORAGE_LINK: 'true'
      AUTORUN_LARAVEL_EVENT_CACHE: 'false'
      AUTORUN_LARAVEL_ROUTE_CACHE: 'false'
      AUTORUN_LARAVEL_VIEW_CACHE: 'false'
      AUTORUN_LARAVEL_CONFIG_CACHE: 'true'
      PHP_POST_MAX_SIZE: '500M'
      PHP_UPLOAD_MAX_FILE_SIZE: '500M'
      PHP_OPCACHE_ENABLE: '1'
    volumes:
      - './secrets/pixelfed/dev.env:/var/www/html/.env'
      - pixelfed-storage:/var/www/html/storage
    networks:
      app:
      db:
      cache:
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'php', 'artisan', 'horizon:status']
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  periodic_dev:
    image: ghcr.io/intentionally-left-nil/pixelfed:0.14.3
    profiles:
      - dev
    env_file: ./secrets/pixelfed/dev.env
    command: ['php', 'artisan', 'schedule:work']
    stop_signal: SIGTERM
    environment:
      AUTORUN_ENABLED: 'false'
      AUTORUN_LARAVEL_MIGRATION: 'false'
      AUTORUN_LARAVEL_MIGRATION_ISOLATION: 'false'
      AUTORUN_LARAVEL_STORAGE_LINK: 'true'
      AUTORUN_LARAVEL_EVENT_CACHE: 'false'
      AUTORUN_LARAVEL_ROUTE_CACHE: 'false'
      AUTORUN_LARAVEL_VIEW_CACHE: 'false'
      AUTORUN_LARAVEL_CONFIG_CACHE: 'true'
      PHP_POST_MAX_SIZE: '500M'
      PHP_UPLOAD_MAX_FILE_SIZE: '500M'
      PHP_OPCACHE_ENABLE: '1'
    volumes:
      - './secrets/pixelfed/dev.env:/var/www/html/.env'
      - pixelfed-storage:/var/www/html/storage
    networks:
      app:
      db:
      cache:
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'healthcheck-schedule']
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  backup_dev:
    build:
      context: './config/backup'
    profiles:
      - dev
    env_file: ./secrets/backup/.env
    environment:
      - BACKUP_ENVIRONMENT=dev
    networks:
      - db
    depends_on:
      db:
        condition: service_healthy
